package com.shamim.entity;
/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

     private Integer userId;
     private String firstName;
     private String lastName;
     private String password;
     private String username;

    public User() {
    }

    public User(String firstName, String lastName, String password, String username) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.username = username;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
}


